config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  devise_for :users

  resources :charities do
    resources :donations
  end
  resources :invitations

  resource :history, only: :show
  resource :dashboard, only: :show
  namespace :dashboard do
    resources :comments
  end

  namespace :my_company do
    resources :charities
  end

end

app/models/charity.rb
class Charity < ActiveRecord::Base
  has_many :donations
  has_many :users, through: :donations

  def self.charity_total_donations_by_user(user)
    joins(:donations).select('charities.*, sum(funds) as total').
    where('donations.user_id = ?', user.id).
    group('charities.id').order('total desc')
  end

  def self.charity_total_donations_by_company(company)
    joins(donations: :user).select('charities.*, sum(funds) as total').
    where('company_id = ?', company.id).
    group('charities.id').order('total desc')
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
  has_many :donations, through: :users
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :charity, touch: true
  belongs_to :user
end

app/models/invitation.rb
class Invitation

  include ActiveModel::Model

  attr_writer :emails

  def emails
    @emails.to_a
  end

  def create
    puts "Creating..."
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :company
  has_many :donations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def require_company_rep!
    @my_company = Company.find_by(admin_id: current_user.id)
    redirect_to charities_path unless @my_company
  end

end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  def index
    @charities = Charity.order('name')
    @additional_params = params[:date] ? { donation_date: params[:date] } : {}
  end
end

app/controllers/dashboard/comments_controller.rb
module Dashboard
  class CommentsController < ApplicationController

    layout 'react'

    def create
      Comment.create(comment_params)
      comments = Comment.order(:id)
      render json: comments
    end

    def index
      comments = Comment.order(:id)
      respond_to do |format|
        format.html
        format.json { render json: comments }
      end
    end

    private

    def comment_params
      params.require(:comment).permit(:author, :text)
    end

  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  layout 'react'

  def show
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  def create
    redirect_to Donation.first
  end

  def show
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController

  def show
    @total_donations = current_user.donations.map(&:funds).sum
    @company_donations = current_user.company ? current_user.try(:company).donations.map(&:funds).sum : 0
    @donations_by_user = Charity.charity_total_donations_by_user(current_user)
    # turn into a hash for fast charity-total lookup
    @donations_by_user = Hash[@donations_by_user.map { |d| [ d.id, d.total ] }]

    @donations_by_company = Charity.charity_total_donations_by_company(current_user.company)
    # turn into a hash for fast charity-total lookup
    #@donations_by_company = Hash[@donations_by_company.map { |d| [ d.id, d.total ] }]
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

  def new
    @invitation = Invitation.new(emails: [ '', '', '' ])
  end

  def create
    @invitation = Invitation.new(invitation_params)
    if @invitation.valid?
      @invitation.create
    else
      puts 1
    end
  end

  private

  def invitation_params
    params.require(:invitation).permit(emails: [])
  end

end

app/controllers/my_company/charities_controller.rb
class MyCompany::CharitiesController < ApplicationController

  before_action :require_company_rep!

  def index
    my_user_donations = Donation.where(user_id: @my_company.users)
    donated_charities = my_user_donations.map(&:charity).uniq
    @charities = donated_charities.map { |c| present_charity(c) }
  end

  private

  def present_charity(charity)
    {
      charity: charity,
      total: charity.donations.map(&:fund_id).sum
    }
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @today = Date.today
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/helpers/dates_helper.rb
module DatesHelper
  def format_date(date)
    date.strftime('%Y-%m-%d')
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/charities/index.html.erb
<h1>Charities</h1>

<ul class="list-charities">
<% @charities.each do |charity| %>
  <% cache [ charity, charity.donations.count ] do %>
    <li class="c">
      <div class="box">
        <div class="content">
          <h4><%= charity.name %></h4>
          <%= link_to 'Donate', charity_donations_path(charity, @additional_params),
                      method: 'post', class: 'btn btn-success' %>
          <div>
            # of donations:
            <%= charity.donations.count %>
          </div>
        </div>
      </div>
    </li>
  <% end %>
<% end %>
</ul>

app/views/donations/create.html.erb
<h1>Donations#create</h1>
<p>Find me in app/views/donations/create.html.erb</p>

app/views/donations/show.html.erb
<h1>Donation</h1>

app/views/histories/show.html.erb
<h1>Donations History</h1>

<% @donations_by_company.each do |charity| %>
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 impact-by-charity">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 impact-by-charity-left">
      <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1 icons">
        <%= charity.name %>
        <div class="glyphicon glyphicon-link"></div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 impact-charity-logo">
        Charity Logo
      </div>
      <p class="col-lg-7 col-md-7 col-sm-7 col-xs-7 impact-charity-name"><%= charity.name %></p>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 impact-by-charity-right">
      <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 donate-by-me">
        <h2>$<%= @donations_by_user[charity.id].to_i %></h2>
        <h6>donated by <strong>me</strong></h6>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 donate-by-company">
        <h2>$<%= charity.total %></h2>
        <h6>donated by <strong><%= current_user.email %></strong></h6>
      </div>
    </div>
  </div>
<% end %>

app/views/invitations/new.html.erb
<%= form_for(@invitation) do |f| %>

  <div id="email-rows">
    <% @invitation.emails.each do |email| %>
      <div class="email-row">
        <input type="text" name="invitation[emails][]" value="<%= email %>"/>
      </div>
    <% end %>
  </div>

  <a href="#" class="link-add-more">Add Another</a>

  <%= f.submit %>

<% end %>

<script>
$('.link-add-more').on('click', function() {
  var lastRow = $('.email-row').last();
  var newRow = lastRow.clone();
  $('input', newRow).val('');
  $('#email-rows').append(newRow);
  return false;
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Charities</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/react.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Charities Dashboard</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://npmcdn.com/react@15.3.0/dist/react.js"></script>
    <script src="https://npmcdn.com/react-dom@15.3.0/dist/react-dom.js"></script>
    <script src="https://npmcdn.com/babel-core@5.8.38/browser.min.js"></script>
    <script src="https://npmcdn.com/remarkable@1.6.2/dist/remarkable.min.js"></script>
    <script src="https://npmcdn.com/react-router/umd/ReactRouter.min.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-fluid">
      <a href="/">Go Back to Welcome page</a>
      <div id="content"></div>
      <script type="text/babel" src="/app.jsx"></script>
    </div>
  </body>
</html>

app/views/my_company/charities/index.html.erb
<h1>Donations made by Users from my Company</h1>

<h2>
  Company: <%= @my_company.name %>
</h2>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Charity</th>
      <th>Total Amount</th>
    </tr>
  </thead>
  <tbody>
<% @charities.each do |rec| %>
  <tr>
    <td><%= rec[:charity].name %></td>
    <td><%= rec[:total] %></td>
  </tr>
<% end %>
  </tbody>
</table>

app/views/welcome/index.html.erb
<div style="float: right;margin:1em;">
  <%= link_to 'React Dashboard', dashboard_path %>
</div>

<h1>Charities App</h1>

<form id="form-select-date" action="<%= charities_path %>">
  <h3>Select Date</h3>
  <div class="form-group">
    <input type="text" name="date" value="<%= format_date(@today) %>"/>
  </div>
  <button class="btn btn-success">
    <span>Set Date</span>&nbsp;<span
    class="glyphicon glyphicon-ok" aria-hidden="true"></span>
  </button>
</form>

<script>
  $('input[name=date]').datepicker({
    format: 'yyyy-mm-dd'
  });
</script>